name: Docker image deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this Github repository
        uses: actions/checkout@v3
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image & push to Docker hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/fso-bloglist-fullstack